language: java

dist: trusty

jdk:
- oraclejdk8
- oraclejdk9

# Java 9 support is still being prepared. Allow failures in Java 9 builds until Java 9 support is finalized...
matrix:
  allow_failures:
    - jdk: oraclejdk9

install: /bin/true

branches:
  only:
  - master

env:
- JAVA_TOOL_OPTIONS="-Xmx2g"

script:
- cd code
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
- mvn test verify --batch-mode
